[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"]

[start]
cmd = "NODE_ENV=production node dist/index.js"
