services:
  - type: web
    name: tahfidz-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_APPS_SCRIPT_URL
        sync: false